# Cloudflare Worker configuration for portfolio API
name = "portfolio-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "16ffea54-0ddc-4807-940b-b6fb383b850c"

# Environment variables
[vars]
CORS_ORIGIN = "https://portfolio-by-lukas.vercel.app"
API_SECRET = "portfolio-api-secret-2024"

# For local development
[env.development]
[env.development.vars]
CORS_ORIGIN = "http://localhost:3000"